version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=django_greet
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
    ports:
      - "5432:5432"
  greetingservice:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/greetingservice
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django_greet
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
    depends_on:
      - db